### ISSUE TITLE
Local VFP database contains a table named "Keywords"

### ISSUE THREAD

**Issue by glennpd** [VFPX/UpsizingWizard#2]
In the UpSqiz.fll when analysing tables in the remoteizename method the "Keywords" file is opened .  If the user's database contains a table of the same name the wizard pukes and fails.

**Comment by DougHennig** [comment]
Hi Glenn. Long time no chat. This should be fixed in a new build I released today: I renamed the built-in tables, such as Keywords.dbf, to have an underscore prefix.
