### ISSUE TITLE
default memo to nVarchar(Max)

### ISSUE THREAD

**Issue by mathiasbanda** [VFPX/UpsizingWizard#3]
Hi all

I tried tweaking the defaults in the table so vfp memo can default to varchar or nvarchar and also wanted dates to default to the proper date in sql and not datetime but couldn't get it to work.

Has anyone managed that please or any advice on what I am missing

KR

mathias

**Comment by DougHennig** [comment]
Did you rebuild UpsizingWizard.app after making the changes to the table?

**Comment by mathiasbanda** [comment]
Yes I did. the changes broke it and it started generating errors - I backed off.

**Comment by DougHennig** [comment]
What changes did you make? The only thing you should have to do is browse _typemap.dbf and change DEFAULT to .F. for the records you don't want as defaults and to .T. for those you do. I just tried it and it worked without error for me.

**Comment by mathiasbanda** [comment]
Okay I see where my mistake lies. I did exactly for memos but then I changed dates to the new(ish) Date for SQL Server. I believe its this latter change that breaks it. I will give it another go in stages, thanks Doug
