### ISSUE TITLE
Tableupdate() query on remote View

### ISSUE THREAD

**Issue by mathiasbanda** [VFPX/UpsizingWizard#6]
Hi all

This isn't a question on the upsizing wizard - no idea where to post general VFP question - sorry.

I am issuing 
Insert Into RempoteView From Name Obj
 llSucess = TableUpdate(0, .T., alias, cArrayError)
llSuccess if true. cArrayError has -1 in there. And of course the record wasn't added to the base table

AERROR( arr) Function thinks nothing is wrong as it creates an array of an error sometime before this code runs. missing variable earlier. I can see the same error before and after my tableupdate() line.

My question is how does one debug this? Using Management studio to insert the same data into the base table works fine.

**Comment by DougHennig** [comment]
You can post general VFP questions at www.foxite.com or www.levelextreme.com.

Doug
