### ISSUE TITLE
Upsizing wizard cannot continue because the log file is full

### ISSUE THREAD

**Issue by barryjaft** [VFPX/UpsizingWizard#7]
Doug, is there a size limit when upsizing? My table is 1.8+GB.
![upsizing wizard error](https://user-images.githubusercontent.com/51342646/66229481-bb196f80-e696-11e9-955d-732a2c42839e.jpg)

**Comment by DougHennig** [comment]
You can try dumping the log and upsizing again to the same database.

**Comment by barryjaft** [comment]
Doug;

 

Turns out I was running out of disk space.

Freed some up and life is good.

 

Thanks for getting back to me,

 

cert and sig
