### ISSUE TITLE
Multiple UQ constraints for one table give error

### ISSUE THREAD

**Issue by GerhardSc** [VFPX/UpsizingWizard#8]
Hello!

I have some tables in VFP that have more than one unique constraint. When upsizing these tables I get error 2714 (an object with the name UQ_tablename is already there) for the second and all following UQ constraints. 
To overcome this problem I want to add the fieldname like

                        lcRmtName = lcRmtName + "_" + lcExpr
after
                        lcRmtName = "UQ_" + THIS.UniqueTableName(chrtran(lcRmtTable, '[]', ''))

Do you expect any problems by this change?

TIA
Gerhard

**Comment by DougHennig** [comment]
The only issue I foresee is that lcExpr is an expression so if it's something like UPPER(FieldName), it won't be a valid name.

**Comment by GerhardSc** [comment]
I see. I also had problems when the expression was consisting of more than one field. And I had to change it to
     `lcRmtName = lcRmtName + "_" + chrtran(lcExpr, '[]', '')`
But this way I got most of the problems solved in my case.
Thanks for a great tool!
Gerhard
