### ISSUE TITLE
Unique Constraint for more than one Field

### ISSUE THREAD

**Issue by GerhardSchmidbauer** [VFPX/UpsizingWizard#9]
Hello,
I have some tables with more than one candidate key in VFP. An example is a country table where ISO code and country name have to be unique each. But that hat gives errors because the name of the UQ constraint has the table name only. To prevent these errors I added 

*!* GS 2020-02-19: Add field name so we can have multiple UQ indexes per table 
*!*	but remove square brackets from field name to prevent names like UQ_table_[field] 
        lcRmtName = lcRmtName + "_" + chrtran(lcExpr, '[]', '')
after
        lcRmtName = "UQ_" + THIS.UniqueTableName(chrtran(lcRmtTable, '[]', ''))

You might want to add this to the master.

Gerhard Schmidbauer

**Comment by DougHennig** [comment]
Thanks, Gerhard. Done.

**Comment by GerhardSc** [comment]
You’re welcome!

 

Kind regards

Mit freundlichen Grüßen

Gerhard Schmidbauer

 

URANUS Software GmbH

Bleichstr. 8 | D-89349 Burtenbach

Tel: +49 8285 92 922

Web:  <http://www.uranus.de/> http://www.uranus.de 

Registergericht Memmingen HRB 12808

USt-ID: DE 128 217 215

 

Von: Doug Hennig <notifications@github.com> 
Gesendet: Mittwoch, 1. April 2020 18:07
An: VFPX/UpsizingWizard <UpsizingWizard@noreply.github.com>
Cc: Subscribed <subscribed@noreply.github.com>
Betreff: Re: [VFPX/UpsizingWizard] Unique Constraint for more than one Field (#9)

 

Thanks, Gerhard. Done.
